//colors in DB
var colors = [
    "White Gold",
    "Red Pebbled",
    "Black",
    "Cream",
    "Black Croco",
    "Heather Grey",
    "Cappuccino",
    "Black to Brown",
    "Brown",
    "Nude",
    "Red",
    "Blue",
    "Cognac",
    "White",
    "Rose Gold",
    "Yellow Gold",
    "Navy",
    "Burgundy",
    "Ivory",
    "Coastal Pink",
    "Washed Blue",
    "Taupe",
    "Camel",
    "Silver",
    "Grey",
    "Peony",
    "Pink",
    "Minimal Pink",
    "Passion Fruit",
    "Rose",
    "Wine",
    "Double Edge Embroidery Navy",
    "Rouching",
    "Bordered",
    "Stone",
    "Light Blue",
    "Gold Vermeil",
    "Soft Pink",
    "Blue Fog",
    "Ballard Blue",
    "Champagne",
    "Military Olive",
    "Soft/Medium",
    "Medium/Firm",
    "Medium",
    "Blush Pink",
    "Blue Stripe",
    "Driftwood",
    "Natural Wood",
    "Double Edge Embroidery White",
    "Dark Charcoal",
    "Light Khaki",
    "Dark Khaki",
    "Double Edge Embroidery Black",
    "Fjord Blue",
    "Ginger",
    "Loden Green",
    "Oatmeal",
    "Heather Rust",
    "Olive",
    "Dusty Blue",
    "Dusty Pink",
    "Light Grey",
    "Charcoal",
    "Sand",
    "Natural",
    "Flax",
    "Bordered Flax",
    "Toasted Almond",
    "Black/Ivory/Toasted Almond",
    "Coco",
    "Indigo",
    "Black/White",
    "Green/Navy",
    "Light Camel",
    "Olive/Black",
    "Green/Black",
    "Navy/Red",
    "Navy/Grey",
    "Black/Grey",
    "Soft Blush",
    "Royal Purple",
    "No Color",
    "Tobacco",
    "Mist",
    "Terracotta",
    "Washed Olive",
    "Heather Navy",
    "Heather Oatmeal",
    "Multi",
    "Steel Blue",
    "Desert Sage",
    "Natural Sand",
    "Natural Indigo",
    "Natural Grey",
    "Navy Multi",
    "Teracotta Multi",
    "Tonal Grey",
    "Tonal Natural",
    "Dusty Blue Multi",
    "Grey Stripe",
    "Silver Multi",
    "Copper Multi",
    "Soft White/Black",
    "Soft White/Terracotta",
    "Vintage Blue Multi",
    "Vintage Multi",
    "Taupe Multi",
    "Black Multi",
    "Midnight Blue Multi",
    "Sandstone Multi",
    "Vintage Blush",
    "Vintage Navy",
    "Vintage Grey",
    "Vintage Sand",
    "Pink Multi",
    "Rose Multi",
    "Rust/Navy",
    "Tan/White",
    "Black/Natural",
    "Indigo Stripe",
    "Slate Stripe",
    "Navy/White",
    "Grey/White",
    "Textured Blue",
    "Textured Grey",
    "Oat Multi",
    "Grey/Cream",
    "Beige Multi",
    "Melon/Blue",
    "Neutral Blue",
    "Rhino Grey",
    "Khaki Tan",
    "Stone Multi",
    "Brown/Cream",
    "Ocean",
    "Copper",
    "Sepia",
    "Natural Stripe",
    "Ivory/Grey",
    "Mocha/White",
    "Hickory/White",
    "White/Hickory",
    "Teal Blue",
    "Blue Multi",
    "Crimson Multi",
    "Mauve",
    "Khaki/Grey",
    "Jute/White",
    "Jute/Black",
    "Tan",
    "Navy Border",
    "White Border",
    "Black Border",
    "Black/White Stripe",
    "Seafoam/Natural",
    "Baked Apple",
    "Vintage Black",
    "Vintage Black",
    "default",
    "Army Green",
    "10 Count",
    "Raw Edge White",
]